[package]
name = "internop"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.25.1"
nalgebra = "0.32.5"
num-complex = "0.4.5"
rand = "0.8.5"
